language: python

sudo: false

env:
  - DJANGO_VERSION=1.8.*
  - DJANGO_VERSION=1.9.*
  - DJANGO_VERSION=1.10rc1

python:
    - "3.4"
    - "3.5"
    - "nightly"

install:
    - pip install -r requirements.txt
    - pip install Django==$DJANGO_VERSION

script: python manage.py test tests

branches:
  only:
    - master
